export const CATEGORY_ICON_NAMES = [
  "UtensilsCrossed",
  "ChefHat",
  "Soup",
  "Salad",
  "Sandwich",
  "Pizza",
  "Hamburger",
  "Beef",
  "Drumstick",
  "Fish",
  "Shrimp",
  "Egg",
  "EggFried",
  "Croissant",
  "Wheat",
  "LeafyGreen",
  "Carrot",
  "Citrus",
  "Apple",
  "Cherry",
  "Grape",
  "Popcorn",
  "Cake",
  "CakeSlice",
  "Cookie",
  "Donut",
  "IceCreamCone",
  "Candy",
  "Coffee",
  "CupSoda",
  "Milk",
  "BottleWine",
] as const;

export type CategoryIconName = (typeof CATEGORY_ICON_NAMES)[number];
