services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: pedidos
      POSTGRES_PASSWORD: pedidos
      POSTGRES_DB: pedidos
    ports:
      - "5452:5432"
    volumes:
      - pedidos_db_data:/var/lib/postgresql/data

volumes:
  pedidos_db_data:
