import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeftIcon, CheckCircle2Icon, XCircleIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { prisma } from "@/lib/prisma";
import { requireTenantAdmin } from "@/lib/require-admin";
import { formatPrice } from "@/lib/format";
import { INQUIRY_STATUS_COLORS, INQUIRY_STATUS_LABELS } from "@/lib/inquiry-status";
import { InquiryEditor } from "../inquiry-editor";

type Answer = { label: string; value: string };
const dateFormatter = new Intl.DateTimeFormat("es-AR", { dateStyle: "medium", timeStyle: "short" });
export default async function InquiryPage({ params }: { params: Promise<{ id: string }> }) {
  const { tenant } = await requireTenantAdmin(); const { id } = await params;
  const inquiry = await prisma.serviceInquiry.findUnique({ where: { id, tenantId: tenant.id }, include: { events: { orderBy: { createdAt: "desc" } } } });
  if (!inquiry) notFound(); const answers = inquiry.answers as unknown as Answer[];
  return <div className="mx-auto flex w-full max-w-5xl flex-col gap-5"><Link href="/admin/consultas" className="flex items-center gap-1.5 self-start text-sm text-muted-foreground hover:text-foreground"><ArrowLeftIcon className="size-4" />Volver a consultas</Link><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold">{inquiry.serviceTitle}</h1><Badge className={INQUIRY_STATUS_COLORS[inquiry.status]}>{INQUIRY_STATUS_LABELS[inquiry.status]}</Badge></div><p className="mt-1 text-sm text-muted-foreground">Recibida el {dateFormatter.format(inquiry.createdAt)}</p></div>{inquiry.quotedAmount && <div className="text-right"><p className="text-xs text-muted-foreground">Presupuesto</p><p className="text-xl font-bold">{formatPrice(Number(inquiry.quotedAmount))}</p></div>}</div><div className="grid items-start gap-5 lg:grid-cols-[1fr_380px]"><div className="flex flex-col gap-5"><section className="rounded-xl border p-5"><h2 className="mb-4 font-semibold">Respuestas recibidas</h2><dl className="divide-y">{answers.map((answer,index) => <div key={`${answer.label}-${index}`} className="grid gap-1 py-3 first:pt-0 last:pb-0 sm:grid-cols-[180px_1fr]"><dt className="text-sm text-muted-foreground">{answer.label}</dt><dd className="whitespace-pre-wrap text-sm font-medium">{answer.value}</dd></div>)}</dl></section><section className="rounded-xl border p-5"><h2 className="mb-3 font-semibold">Avisos</h2><div className="flex flex-wrap gap-4 text-sm"><span className="flex items-center gap-2">{inquiry.telegramSent ? <CheckCircle2Icon className="size-4 text-emerald-500" /> : <XCircleIcon className="size-4 text-muted-foreground" />}Telegram</span><span className="flex items-center gap-2">{inquiry.emailSent ? <CheckCircle2Icon className="size-4 text-emerald-500" /> : <XCircleIcon className="size-4 text-muted-foreground" />}Email</span></div>{inquiry.notificationError && <p className="mt-3 text-xs text-destructive">{inquiry.notificationError}</p>}</section><section className="rounded-xl border p-5"><h2 className="mb-3 font-semibold">Historial</h2><div className="flex flex-col gap-3">{inquiry.events.map(event => <div key={event.id} className="flex items-start justify-between gap-3 border-l-2 border-muted pl-3"><div><p className="text-sm font-medium">{INQUIRY_STATUS_LABELS[event.status]}{event.quotedAmount ? ` · ${formatPrice(Number(event.quotedAmount))}` : ""}</p>{event.notes && <p className="mt-0.5 line-clamp-2 text-xs text-muted-foreground">{event.notes}</p>}</div><time className="shrink-0 text-xs text-muted-foreground">{dateFormatter.format(event.createdAt)}</time></div>)}</div></section></div><InquiryEditor id={id} status={inquiry.status} quotedAmount={inquiry.quotedAmount ? String(inquiry.quotedAmount) : ""} internalNotes={inquiry.internalNotes ?? ""} /></div></div>;
}
